In [1]:
import pandas as pd
import numpy as np 
np.random.randn(5,3)

array([[ 0.71231645,  1.31180838,  0.71092828],
       [-0.13600655, -0.21155854,  0.93310119],
       [-2.18073276, -2.57760751, -1.02837564],
       [ 1.46114935, -0.14245938,  0.84257658],
       [-0.21122575,  0.68988267,  0.46283935]])

In [3]:
import pandas as pd
data=pd.DataFrame(np.random.randn(5,3))
print(data)

          0         1         2
0 -0.376250 -1.720974 -1.765962
1  1.331307 -1.765216  1.975069
2 -0.521207 -0.864690  1.146874
3  0.858428  1.103556 -0.124118
4  1.350189 -0.098289 -2.763810


In [16]:
import pandas as pd
data1=pd.DataFrame(np.random.randn(6,6),columns=["col1","col2","col3","col4","col5","col6"])
data1.ndim
data1.dtypes
data1.shape
data1.head(2)
data1.tail(5)


col1      col2      col3      col4      col5      col6
1  1.101757 -0.114377 -0.440946 -0.874502 -0.543409  1.072262
2 -1.276609  0.035016  1.528221 -0.791904 -0.830342 -1.151479
3 -1.683169  0.436559 -0.911448  1.259252 -0.441782  0.551385
4 -0.946583 -1.092283  0.192503 -0.556278 -0.583994 -0.546317
5  0.525739  0.772538 -0.226763  1.248338 -0.535391  0.698918

In [24]:
data1.apply(np.mean)
# data1.apply(np.median)

col1   -0.257270
col2   -0.039681
col3   -0.017130
col4    0.281480
col5   -0.539400
col6    0.540966
dtype: float64

In [25]:
data1.apply(np.median)

col1   -0.257270
col2   -0.039681
col3   -0.017130
col4    0.281480
col5   -0.539400
col6    0.540966
dtype: float64

In [26]:
data1.apply(np.amin)

col1   -1.683169
col2   -1.594670
col3   -0.911448
col4   -0.874502
col5   -0.830342
col6   -1.151479
dtype: float64

In [27]:
data1.apply(np.absolute)

col1      col2      col3      col4      col5      col6
0  0.432043  1.594670  1.316408  1.119237  0.144811  0.530546
1  1.101757  0.114377  0.440946  0.874502  0.543409  1.072262
2  1.276609  0.035016  1.528221  0.791904  0.830342  1.151479
3  1.683169  0.436559  0.911448  1.259252  0.441782  0.551385
4  0.946583  1.092283  0.192503  0.556278  0.583994  0.546317
5  0.525739  0.772538  0.226763  1.248338  0.535391  0.698918

In [28]:
data1.apply(np.angle)

col1      col2      col3      col4      col5      col6
0  0.000000  3.141593  0.000000  0.000000  3.141593  0.000000
1  0.000000  3.141593  3.141593  3.141593  3.141593  0.000000
2  3.141593  0.000000  0.000000  3.141593  3.141593  3.141593
3  3.141593  0.000000  3.141593  0.000000  3.141593  0.000000
4  3.141593  3.141593  0.000000  3.141593  3.141593  3.141593
5  0.000000  0.000000  3.141593  0.000000  3.141593  0.000000

In [30]:
data1.apply(np.acosh)

col1  col2      col3      col4  col5      col6
0       NaN   NaN  0.775888  0.483612   NaN       NaN
1  0.447384   NaN       NaN       NaN   NaN  0.377909
2       NaN   NaN  0.987249       NaN   NaN       NaN
3       NaN   NaN       NaN  0.705358   NaN       NaN
4       NaN   NaN       NaN       NaN   NaN       NaN
5       NaN   NaN       NaN  0.690927   NaN       NaN

In [33]:
data1.__deepcopy__

<bound method NDFrame.__deepcopy__ of        col1      col2      col3      col4      col5      col6
0  0.432043 -1.594670  1.316408  1.119237 -0.144811  0.530546
1  1.101757 -0.114377 -0.440946 -0.874502 -0.543409  1.072262
2 -1.276609  0.035016  1.528221 -0.791904 -0.830342 -1.151479
3 -1.683169  0.436559 -0.911448  1.259252 -0.441782  0.551385
4 -0.946583 -1.092283  0.192503 -0.556278 -0.583994 -0.546317
5  0.525739  0.772538 -0.226763  1.248338 -0.535391  0.698918>

In [40]:
data1.apply(lambda x:x.max())

col1    1.101757
col2    0.772538
col3    1.528221
col4    1.259252
col5   -0.144811
col6    1.072262
dtype: float64

In [41]:
data1.apply(lambda x:x.max()-x.min())

col1    2.784926
col2    2.367208
col3    2.439669
col4    2.133754
col5    0.685531
col6    2.223741
dtype: float64

In [44]:
data1["col1"].apply(lambda x:x+2)

0    2.432043
1    3.101757
2    0.723391
3    0.316831
4    1.053417
5    2.525739
Name: col1, dtype: float64

In [49]:
# import pandas as pd
df=data1["col1"].map(lambda x:x*100)
df.apply(np.mean)


0     43.204281
1    110.175679
2   -127.660922
3   -168.316891
4    -94.658343
5     52.573941
Name: col1, dtype: float64

In [54]:
import pandas as pd 
data1.reindex(index=["a","b","c","d","e","f"])

col1  col2  col3  col4  col5  col6
a   NaN   NaN   NaN   NaN   NaN   NaN
b   NaN   NaN   NaN   NaN   NaN   NaN
c   NaN   NaN   NaN   NaN   NaN   NaN
d   NaN   NaN   NaN   NaN   NaN   NaN
e   NaN   NaN   NaN   NaN   NaN   NaN
f   NaN   NaN   NaN   NaN   NaN   NaN

In [1]:
import pandas as pd
technologies=({"course":["spark","pyspark","hadoop","pandas"],
               "fee":['22000','25000','29000','26000'],
               "duration":['30days','50days','40days','60days'],
               "discount":['1000','2300','2500','1400']
})
df=pd.DataFrame(technologies,index=['r1','r2','r3','r4'])
print(df)

     course    fee duration discount
r1    spark  22000   30days     1000
r2  pyspark  25000   50days     2300
r3   hadoop  29000   40days     2500
r4   pandas  26000   60days     1400


In [2]:
df1=df.reindex(["r1","r2","r3","r4"])
df1

course    fee duration discount
r1    spark  22000   30days     1000
r2  pyspark  25000   50days     2300
r3   hadoop  29000   40days     2500
r4   pandas  26000   60days     1400

In [3]:
df1=df.reindex(["r1","r2","r3","r4"],fill_value='testing')
print(df1)

       course      fee duration discount
r1      spark    22000   30days     1000
raw2  testing  testing  testing  testing
r3     hadoop    29000   40days     2500
r4     pandas    26000   60days     1400


In [4]:
import numpy as np
import pandas as pd
df=np.random.randn(8,4)
print(df)

[[-0.37661035 -2.08612758  0.20109719 -0.81947733]
 [-2.64524586  0.21086673 -0.8042593  -0.92803125]
 [ 1.12984121 -0.40211176  0.03311871 -0.76284386]
 [ 0.93657488  0.55817665 -1.2378239   1.5924609 ]
 [-1.64893741 -0.6582245   0.69442067 -0.80873446]
 [-0.55892929 -1.77434338  1.03646897 -0.45546844]
 [ 1.41791693  0.27361005  0.48191548 -0.13016171]
 [-1.28906074  1.12375746 -0.84215255  1.85537346]]


In [5]:
df=pd.DataFrame(np.random.randn(8,4),index=['a','b','c','d','e','f','g','h'],
                columns=['A','B','C','D'])
print(df)

          A         B         C         D
a -0.047298 -0.337238 -0.614329  0.552346
b  1.252937  0.474900 -0.672114 -0.960918
c  1.030967 -0.460882 -1.015377  0.193077
d -1.113995 -1.244036 -0.934253  1.167855
e -0.799208  0.944355 -0.184532 -0.472719
f  1.087347  0.109004  0.785883 -1.208417
g  0.302327 -0.189549  0.250081  0.511829
h  0.886868  0.736110 -1.288674 -0.018964


In [10]:
import pandas as pd
# df.loc[rows,cols] # type: ignore
df.loc[:,['A','C']]
df.loc[['a','b','g','h'],['A','C']]
df.loc['a':'h']

A         B         C         D
a -0.047298 -0.337238 -0.614329  0.552346
b  1.252937  0.474900 -0.672114 -0.960918
c  1.030967 -0.460882 -1.015377  0.193077
d -1.113995 -1.244036 -0.934253  1.167855
e -0.799208  0.944355 -0.184532 -0.472719
f  1.087347  0.109004  0.785883 -1.208417
g  0.302327 -0.189549  0.250081  0.511829
h  0.886868  0.736110 -1.288674 -0.018964

In [11]:
df.loc['a']>0

A    False
B    False
C    False
D     True
Name: a, dtype: bool

In [14]:
df.loc['a':'C']

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [15]:
df.iloc[0,2]

np.float64(-0.6143285194022159)

In [16]:
df.iloc[:4]

A         B         C         D
a -0.047298 -0.337238 -0.614329  0.552346
b  1.252937  0.474900 -0.672114 -0.960918
c  1.030967 -0.460882 -1.015377  0.193077
d -1.113995 -1.244036 -0.934253  1.167855

In [17]:
df.iloc[1:5,2:4]

C         D
b -0.672114 -0.960918
c -1.015377  0.193077
d -0.934253  1.167855
e -0.184532 -0.472719

In [18]:
df.iloc[:,1:3]

B         C
a -0.337238 -0.614329
b  0.474900 -0.672114
c -0.460882 -1.015377
d -1.244036 -0.934253
e  0.944355 -0.184532
f  0.109004  0.785883
g -0.189549  0.250081
h  0.736110 -1.288674

In [3]:
# concatination of two dataframes
import pandas as pd
one=pd.DataFrame({
    "Name":['Alex','Any','Allen','Alice','Ayoung'],
    "Subject_id":['sub1','sub2','sub4','sub5','sub6'],
    "Marks_scored":[98,90,87,69,78]},
    index=[1,2,3,4,5])
two=pd.DataFrame({
    "Name":['Billy','Brian','Bran','Bryce','Betty'],
    "Sub_id":['sub1','sub4','sub3','sub6','sub5'],
    "Marks_scored":[89,80,79,97,88],})

print(one)
print()
print(two)

     Name Subject_id  Marks_scored
1    Alex       sub1            98
2     Any       sub2            90
3   Allen       sub4            87
4   Alice       sub5            69
5  Ayoung       sub6            78

    Name Sub_id  Marks_scored
0  Billy   sub1            89
1  Brian   sub4            80
2   Bran   sub3            79
3  Bryce   sub6            97
4  Betty   sub5            88


In [4]:
# we can concat two dataframes in two ways
# 1.Horizontal concat
# 2.Vertical concate
pd.concat([one,two])

Name Subject_id  Marks_scored Sub_id
1    Alex       sub1            98    NaN
2     Any       sub2            90    NaN
3   Allen       sub4            87    NaN
4   Alice       sub5            69    NaN
5  Ayoung       sub6            78    NaN
0   Billy        NaN            89   sub1
1   Brian        NaN            80   sub4
2    Bran        NaN            79   sub3
3   Bryce        NaN            97   sub6
4   Betty        NaN            88   sub5

In [7]:
pd.concat([one,two],keys=['x','y'])

Name Subject_id  Marks_scored Sub_id
x 1    Alex       sub1            98    NaN
  2     Any       sub2            90    NaN
  3   Allen       sub4            87    NaN
  4   Alice       sub5            69    NaN
  5  Ayoung       sub6            78    NaN
y 0   Billy        NaN            89   sub1
  1   Brian        NaN            80   sub4
  2    Bran        NaN            79   sub3
  3   Bryce        NaN            97   sub6
  4   Betty        NaN            88   sub5

In [8]:
pd.concat([one,two],keys=["x","y"])


Name Subject_id  Marks_scored Sub_id
x 1    Alex       sub1            98    NaN
  2     Any       sub2            90    NaN
  3   Allen       sub4            87    NaN
  4   Alice       sub5            69    NaN
  5  Ayoung       sub6            78    NaN
y 0   Billy        NaN            89   sub1
  1   Brian        NaN            80   sub4
  2    Bran        NaN            79   sub3
  3   Bryce        NaN            97   sub6
  4   Betty        NaN            88   sub5

In [10]:
# pd.concat([one,two],ignore_index=True)
pd.concat([one,two],axis=1)

Name Subject_id  Marks_scored   Name Sub_id  Marks_scored
1    Alex       sub1          98.0  Brian   sub4          80.0
2     Any       sub2          90.0   Bran   sub3          79.0
3   Allen       sub4          87.0  Bryce   sub6          97.0
4   Alice       sub5          69.0  Betty   sub5          88.0
5  Ayoung       sub6          78.0    NaN    NaN           NaN
0     NaN        NaN           NaN  Billy   sub1          89.0