In [2]:
import pandas as pd
data=[23,24,34,56,21,45,78,60,70,79,32]
print(data)

[23, 24, 34, 56, 21, 45, 78, 60, 70, 79, 32]


In [ ]:
data1=pd.read_csv('titanic.csv')
print(data1)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [7]:
data2=[12,13,54,76,87,89,90,78]
data2.sort()

In [8]:
data2

[12, 13, 54, 76, 78, 87, 89, 90]

In [12]:
data2_copy=data2.copy()

In [13]:
data2_copy

[12, 13, 54, 76, 78, 87, 89, 90]

In [15]:
# mean
# Mode
# median
import numpy as np
np.mean(data2)

np.float64(62.375)

In [16]:
import numpy as np
round(np.mean(data2),2)

np.float64(62.38)

In [19]:
# calculate a mean of the data 
data3=[30,87,90,30,67,35,67]
import numpy as np
round(np.mean(data3),2)

np.float64(58.0)

In [22]:
np.median(data3)


np.float64(67.0)

In [23]:
data3

[30, 87, 90, 30, 67, 35, 67]

In [26]:
n=7
(n+1)/2

4.0

In [27]:
# mode of the data
data3

[30, 87, 90, 30, 67, 35, 67]

In [31]:
import numpy as snp
from statistics import mode
mode(data3)

30

In [32]:
data4=[10,20,40,50,60,70,80,90]
from statistics import mode
mode(data4)

10

In [33]:
# dispersion of the data

# 1. percentile of the data
# 2. std dev
# 3.variance
data2_copy

[12, 13, 54, 76, 78, 87, 89, 90]

In [37]:
np.percentile(data2_copy,[67,40])

array([84.21, 71.6 ])

In [36]:
np.percentile(data2_copy,[25,50])

array([43.75, 77.  ])

In [41]:
q3=np.percentile(data2_copy,[75])
q1=np.percentile(data2_copy,[25])
IQR=q3-q1

In [42]:
IQR

array([43.75])

In [ ]:
upper_bound=(IQR+1.5*q3)
upper_bound=(IQR-1.5*q1)



In [ ]:
q1=32
q2=50
q3=75
IQR=q3-q1
print(f'my IQR value is {IQR}')
lower_bound=q1-(1.5*IQR)
print(lower_bound)
upper_bound=q3+(1.5*IQR)
print(upper_bound)


my IQR value is 43
-32.5
139.5


In [54]:
data5=[-1,-2,-7,-9,1,4,5,6,8,10]

In [55]:

outlier=[]
lower_bound=-4.0
upper_bound=92.0
for i in data5:
    if i>upper_bound:
        outlier.append(i)
    if i<lower_bound:
        outlier.append(i)    
print(outlier)        

[-7, -9]
